#!/bin/sh

function installright() {
    RIGHT=$1
    RULE=$2
    
    /usr/bin/security authorizationdb read $RIGHT >/dev/null 2>&1 && return 0
    
    echo "Installing right $RIGHT defaulting to rule $RULE" >&2
    /usr/bin/security authorizationdb write $RIGHT $RULE
}

echo "Installing rights into authorization database if necessary" >&2
installright ch.znerol.rotavault.monitor allow
installright ch.znerol.rotavault.manage default

echo "Loading launchd job for privelegd helper tool ch.znerol.rotavault" >&2
/bin/launchctl load /Library/LaunchDaemons/ch.znerol.rotavault.plist
